parameters:
#    south_hills_our_database.example.class: SouthHills\OurDatabaseBundle\Example

services:
#    south_hills_our_database.example:
#        class: %south_hills_our_database.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
