parameters:
#    south_hills_our_second.example.class: SouthHills\OurSecondBundle\Example

services:
#    south_hills_our_second.example:
#        class: %south_hills_our_second.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
