parameters:
#    south_hills_our_first.example.class: SouthHills\OurFirstBundle\Example

services:
#    south_hills_our_first.example:
#        class: %south_hills_our_first.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
